export const GET_NEXT_TEXT = 'GET_NEXT_TEXT'
export const GET_ACTION_BUTTONS = 'GET_ACTION_BUTTONS'
export const CHANGE_CURRENT_STATE = 'CHANGE_CURRENT_STATE'
export const RESET_GAME_PROGRESS = "RESET_GAME_PROGRESS"

