export const MODE_PAGE = 'MODE_PAGE'
export const OPTIONS_PAGE = 'OPTIONS_PAGE'
export const OPTIONS_CHOOSE_LANGUAGE_PAGE = 'OPTIONS_PAGE'
export const GAME_PAGE = 'GAME_PAGE'
export const SHOW_OPTIONS_SECTION = 'SHOW_OPTIONS_SECTION'


export const CHANGE_CURRENT_PAGE = 'CHANGE_CURRENT_PAGE'
